services:
  - type: web
    name: lernio
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn run:app --bind=0.0.0.0:10000 --workers=2 --threads=2 --timeout=120
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
    disk:
      name: data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
