services:
  - type: web
    name: lernio
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn run:app -c gunicorn_config.py
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
