"""Add StudentWork model

Revision ID: 1c9eebd91056
Revises: 98fefca77c98
Create Date: 2025-05-26 22:04:24.716686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9eebd91056'
down_revision = '98fefca77c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('is_graded', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_works', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_works_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_works_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_works_submitted_at'), ['submitted_at'], unique=False)

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('student_works', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_works_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_student_works_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_works_material_id'))

    op.drop_table('student_works')
    # ### end Alembic commands ###
