"""Add retake status to Submission

Revision ID: 35e675b76db3
Revises: 1442af585819
Create Date: 2025-04-28 19:44:21.563331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e675b76db3'
down_revision = '1442af585819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retake_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('retake_requested_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_submissions_retake_status'), ['retake_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_retake_status'))
        batch_op.drop_column('retake_requested_at')
        batch_op.drop_column('retake_status')

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.alter_column('lesson_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
