"""Add LoginHistory model

Revision ID: 93ba0945b877
Revises: 35e675b76db3
Create Date: 2025-05-17 22:01:28.905679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ba0945b877'
down_revision = '35e675b76db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_group_chat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('last_read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_participants_user_id'), ['user_id'], unique=False)

    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glossary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('definition_ru', sa.Text(), nullable=False),
    sa.Column('definition_uz', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wrong_option1', sa.Text(), nullable=True),
    sa.Column('wrong_option2', sa.Text(), nullable=True),
    sa.Column('wrong_option3', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_glossary_items_material_id'), ['material_id'], unique=False)

    op.create_table('material_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_questions_material_id'), ['material_id'], unique=False)

    op.create_table('material_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('read_by_teacher', sa.Boolean(), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['material_questions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_answers_student_id'), ['student_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_system_message', sa.Boolean(), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.Column('material_answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['material_answer_id'], ['material_answers.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sent_at'), ['sent_at'], unique=False)

    op.create_table('message_read_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', name='_message_user_uc')
    )
    with op.batch_alter_table('message_read_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_read_status_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_read_status_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_video_lesson', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('video_source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('evaluation_criteria', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('evaluation_criteria')
        batch_op.drop_column('video_source')
        batch_op.drop_column('is_video_lesson')

    with op.batch_alter_table('message_read_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_read_status_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_read_status_message_id'))

    op.drop_table('message_read_status')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_sent_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('material_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_answers_student_id'))
        batch_op.drop_index(batch_op.f('ix_material_answers_question_id'))

    op.drop_table('material_answers')
    with op.batch_alter_table('material_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_questions_material_id'))

    op.drop_table('material_questions')
    with op.batch_alter_table('glossary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_glossary_items_material_id'))

    op.drop_table('glossary_items')
    op.drop_table('login_history')
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_participants_conversation_id'))

    op.drop_table('chat_participants')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
